const assert = require('assert');
const { describe, it, setup, suite } = require('mocha');

const plugin = require('../plugins/do_figlet.js');

// Trailing whites are generated by the figlet tool,
// they must be kept in the expected result.
const RENDERED = `\`\`\`  _            _   
 | |_ ___  ___| |_ 
 | __/ _ \\/ __| __|
 | ||  __/\\__ \\ |_ 
  \\__\\___||___/\\__|
                   \`\`\``;


suite('Figlet Plugin Tests', function () {
    setup(function () {
        this.bot = {
            self: {
                id: 'bosta',
            },
        };

        this.rtm = {
            sent: [],
            sendMessage(message, channel) {
                this.sent.push([message, channel]);
            },
        };
    });

    describe('on figlet message', function () {
        it('should render back to same channel', function () {
            const message = { text: '<@bosta> figlet test', channel: 'general' };
            const rtm = this.rtm;
            return plugin.handleFiglet(this.bot, this.rtm, message)
                .then(() => {
                    assert.deepEqual([RENDERED, 'general'], rtm.sent[0]);
                });
        });
    });

    describe('on figlet with empty text', function () {
        it('should do nothing', function () {
            const message = { text: '<@bosta> figlet', channel: 'general' };
            const rtm = this.rtm;
            return plugin.handleFiglet(this.bot, this.rtm, message)
                .catch(() => {
                    assert.deepEqual([], rtm.sent);
                });
        });
    });
});
